from typing import Protocol
from domain.trade import TradeIntent
from domain.order import Order
from adapters.deriv.models import AccountSnapshot, ClosedContract, Proposal, ContractSnapshot, ReconciliationResult


class DerivAdapter(Protocol):
    account_id: str | None
    async def get_tick(self, symbol: str, subscribe: bool = False) -> dict: ...
    async def get_candles(self, symbol: str, granularity: int, count: int) -> list: ...
    async def get_account(self) -> AccountSnapshot: ...
    async def get_open_contracts(self) -> tuple: ...
    async def get_statement(self, since: int) -> list: ...
    async def get_closed_contracts(self) -> list[ClosedContract]: ...
    async def get_proposal(self, intent: TradeIntent) -> Proposal: ...
    async def place_order(self, intent: TradeIntent, order: Order) -> dict: ...
    async def close_order(self, intent: TradeIntent, order: Order) -> dict: ...
    async def get_contract(self, contract_id: int) -> ContractSnapshot: ...
    async def resolve_order(self, order: Order, intent: TradeIntent) -> ReconciliationResult: ...
